### ISSUE TITLE
use /entity/ instead of /wiki/ in Wikidata URIs

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/eco_de#3]
base uri of wikidata entities should be `https://www.wikidata.org/entity/` followed by the Q-Number, not `wiki` which is the page about an entity.

e.g. https://www.wikidata.org/wiki/Q1167748 should be https://www.wikidata.org/entity/Q1167748
When dereferencing /entity/ wikidata issues a seeOther redirect, which is the semantically correct behaviour, see https://www.w3.org/TR/cooluris/

**Comment by DanilSko** [comment]
fixed: 
1. https://github.com/dracor-org/eco_de/commit/629625dc8aff728315f2fb321fc4547267f12caf
2. https://github.com/dracor-org/eco_en/commit/a001e9861bb2abb4f445500fb6c5a04887eb4047
