### ISSUE TITLE
Fix distinction between group and chapter divs

### ISSUE THREAD

**Issue by cmil** [dracor-org/eco_de#6]
Some texts that only consist of chapters mark the respective divs with a `type` attribute set to "group", e.g.   [1897_Fontane_Stechlin.xml](https://github.com/EcoCor/eco-de/blob/main/tei/1897_Fontane_Stechlin.xml). This should be corrected to "chapter".

**Comment by DanilSko** [comment]
Fixed in Dolomiten, Salander, Stechlin, Bergwerke, Dolomiten, Asteroiden-Roman etc. here: https://github.com/EcoCor/eco-de/commit/f878052d9e60eae0d15e3d82984dc9a39cc6af40
