### ISSUE TITLE
Empty <body/> in 1913_Kellermann_Tunnel.xml

### ISSUE THREAD

**Issue by cmil** [dracor-org/eco_de#7]
The entire text in [1913_Kellermann_Tunnel.xml](https://github.com/EcoCor/eco-de/blob/main/tei/1913_Kellermann_Tunnel.xml) is contained in the `<front>` element. It should be moved to the `<body>`.

**Comment by DanilSko** [comment]
Fixed here: https://github.com/EcoCor/eco-de/commit/8c98999f1e92e1a2578cfd2e3b80f1b174a51b35
