### ISSUE TITLE
Fix markup in 1877_Spielhagen_Sturmflut.xml

### ISSUE THREAD

**Issue by cmil** [dracor-org/eco_de#8]
The `head` for "Drittes Buch" contains more text than it probably should:

https://github.com/EcoCor/eco-de/blob/0141d1b32d68f36735996b3f9128a84a63e3c2b3/tei/1877_Spielhagen_Sturmflut.xml#L2548-L2550

**Comment by DanilSko** [comment]
Fixed here https://github.com/EcoCor/eco-de/commit/a0679b2eef2e68a847e2f43b9a4f4e92d7034bd9
